# Generated by Django 6.0.3 on 2026-04-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_digitalcv_experiences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedinstitutiondomain',
            name='domain',
        ),
        migrations.AddField(
            model_name='allowedinstitutiondomain',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
