# Generated by Django 6.0.3 on 2026-05-05 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_attestation_file_and_more'),
        ('conventions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='applications.application'),
        ),
    ]
