# Generated by Django 6.0.3 on 2026-04-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_companyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attestation_file',
            field=models.FileField(blank=True, null=True, upload_to='attestations/'),
        ),
        migrations.AddField(
            model_name='application',
            name='attestation_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='application',
            name='report_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='report_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_state',
            field=models.CharField(default='convention_to_sign', max_length=30),
        ),
    ]
