# Generated by Django 6.0.3 on 2026-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='internship_type',
            field=models.CharField(choices=[('INTERNSHIP', 'Stage professionnel'), ('ALTERNANCE', 'Contrat en alternance'), ('FINAL_YEAR', "Projet de Fin d'Études (PFE)")], default='INTERNSHIP', max_length=20),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
