# Generated by Django 6.0.3 on 2026-03-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('student_agreement', models.FileField(blank=True, null=True, upload_to='agreements/students/')),
                ('company_agreement', models.FileField(blank=True, null=True, upload_to='agreements/companies/')),
                ('validation_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
