# Generated by Django 6.0.3 on 2026-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_internshipoffer_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
